# Generated by Django 3.1 on 2021-02-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='rec_id',
            new_name='oid',
        ),
        migrations.RenameField(
            model_name='siterecs_other_srcs',
            old_name='rec_id',
            new_name='oid',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_ftloc',
            old_name='rec_id',
            new_name='oid',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='rec_id',
            new_name='oid',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='site_id',
            new_name='oid',
        ),
    ]
