# Generated by Django 3.1.7 on 2021-03-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0003_auto_20210225_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_avail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_bupe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_misc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_mtd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_ntrex',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='dbhids_tad_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_dbhids_tad'),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='fqhc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='hfp_fqhc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_hfp_fqhc'),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mat_avail',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mat_bupe',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mat_mtd',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mat_ntrex',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='other_srcs_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_other_srcs'),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='samhsa_ftloc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_samhsa_ftloc'),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='samhsa_otp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_samhsa_otp'),
        ),
    ]
