# Generated by Django 3.1.7 on 2021-03-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0004_auto_20210302_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterecs_samhsa_ftloc',
            name='any_mat',
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='sa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='add_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='db_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='phone_intake1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='phone_intake2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='pi_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='zip4',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='zip5',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
