# Generated by Django 3.1.7 on 2021-03-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0005_auto_20210302_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites_all',
            name='samhsa_ftloc_id',
        ),
        migrations.AddField(
            model_name='sites_all',
            name='samhsa_ftloc_id',
            field=models.ManyToManyField(to='bupehandler.Siterecs_samhsa_ftloc'),
        ),
        migrations.CreateModel(
            name='Sites_ftloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_samhsa_ftloc')),
                ('samhsa_ftloc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.sites_all')),
            ],
            options={
                'db_table': 'sites_ftloc',
                'managed': True,
            },
        ),
    ]
