# Generated by Django 3.1.7 on 2021-03-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0006_auto_20210303_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sites_ftloc',
        ),
    ]
