# Generated by Django 3.1.7 on 2021-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0007_delete_sites_ftloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='date_firstfind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='date_lastfind',
            field=models.DateField(blank=True, null=True),
        ),
    ]
