# Generated by Django 3.1.7 on 2021-03-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0008_auto_20210303_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites_all',
            name='samhsa_otp_id',
        ),
        migrations.AddField(
            model_name='sites_all',
            name='samhsa_otp_id',
            field=models.ManyToManyField(blank=True, null=True, to='bupehandler.Siterecs_samhsa_otp'),
        ),
    ]
