# Generated by Django 3.1.7 on 2021-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0011_auto_20210309_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='date_firstfind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='date_lastfind',
            field=models.DateField(blank=True, null=True),
        ),
    ]
