# Generated by Django 3.1.7 on 2021-03-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0012_auto_20210309_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites_all',
            name='dbhids_tad_id',
        ),
        migrations.AddField(
            model_name='sites_all',
            name='dbhids_tad_id',
            field=models.ManyToManyField(to='bupehandler.Siterecs_dbhids_tad'),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='samhsa_otp_id',
            field=models.ManyToManyField(to='bupehandler.Siterecs_samhsa_otp'),
        ),
        migrations.CreateModel(
            name='Siterecs_dbhids_sites_all_lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_sites_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.sites_all')),
                ('site_id_samhsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_dbhids_tad')),
            ],
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='site_id',
            field=models.ManyToManyField(through='bupehandler.Siterecs_dbhids_sites_all_lookup', to='bupehandler.Sites_all'),
        ),
    ]
