# Generated by Django 3.1.7 on 2021-03-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0013_auto_20210309_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites_all',
            name='hfp_fqhc_id',
        ),
        migrations.AddField(
            model_name='sites_all',
            name='hfp_fqhc_id',
            field=models.ManyToManyField(to='bupehandler.Siterecs_hfp_fqhc'),
        ),
        migrations.CreateModel(
            name='Siterecs_hfp_fqhc_sites_all_lookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid_sites_all', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.sites_all')),
                ('site_id_samhsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_hfp_fqhc')),
            ],
        ),
        migrations.AddField(
            model_name='siterecs_hfp_fqhc',
            name='site_id',
            field=models.ManyToManyField(through='bupehandler.Siterecs_hfp_fqhc_sites_all_lookup', to='bupehandler.Sites_all'),
        ),
    ]
