# Generated by Django 3.1.7 on 2021-03-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0015_auto_20210309_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterecs_dbhids_sites_all_lookup',
            old_name='oid_sites_all',
            new_name='dbhids_tad_id',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_sites_all_lookup',
            old_name='site_id_samhsa',
            new_name='site_id_samhsa_dbhids',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc_sites_all_lookup',
            old_name='oid_sites_all',
            new_name='hfp_fqhc_id',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc_sites_all_lookup',
            old_name='site_id_samhsa',
            new_name='site_id_samhsa_hfp',
        ),
        migrations.RenameField(
            model_name='sites_site_recs_lookup',
            old_name='site_id_samhsa',
            new_name='site_id_samhsa_st',
        ),
        migrations.RenameField(
            model_name='sitesrecs_other_srcs_sitesall_lk',
            old_name='site_id_samhsa',
            new_name='site_id_samhsa_recs',
        ),
    ]
