# Generated by Django 3.1.7 on 2021-03-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0016_auto_20210310_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites_ftloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samhsa_ftloc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.sites_all')),
                ('samhsa_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.siterecs_samhsa_ftloc')),
            ],
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='site_id',
            field=models.ManyToManyField(through='bupehandler.Sites_ftloc', to='bupehandler.Sites_all'),
        ),
    ]
