# Generated by Django 3.1.7 on 2021-03-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0017_auto_20210310_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterecs_dbhids_sites_all_lookup',
            old_name='site_id_samhsa_dbhids',
            new_name='samhsa_oid',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_sites_all_lookup',
            old_name='dbhids_tad_id',
            new_name='sites_all_id',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc_sites_all_lookup',
            old_name='site_id_samhsa_hfp',
            new_name='samhsa_oid',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc_sites_all_lookup',
            old_name='hfp_fqhc_id',
            new_name='sites_all_id',
        ),
        migrations.RenameField(
            model_name='sites_ftloc',
            old_name='samhsa_ftloc_id',
            new_name='sites_all_id',
        ),
        migrations.RenameField(
            model_name='sites_site_recs_lookup',
            old_name='site_id_samhsa_st',
            new_name='samhsa_oid',
        ),
        migrations.RenameField(
            model_name='sites_site_recs_lookup',
            old_name='oid_sites_all',
            new_name='sites_all_id',
        ),
        migrations.RenameField(
            model_name='sitesrecs_other_srcs_sitesall_lk',
            old_name='site_id_samhsa_recs',
            new_name='samhsa_oid',
        ),
        migrations.RenameField(
            model_name='sitesrecs_other_srcs_sitesall_lk',
            old_name='other_srcs_id',
            new_name='sites_all_id',
        ),
    ]
