# Generated by Django 3.1.7 on 2021-03-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0018_auto_20210310_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites_all',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
