# Generated by Django 3.1.7 on 2021-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0019_auto_20210310_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites_all',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
