# Generated by Django 3.1.7 on 2021-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0022_auto_20210315_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites_all',
            name='address_suppl',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
