# Generated by Django 3.1.7 on 2021-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0023_auto_20210315_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterecs_hfp_fqhc',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='loc_suppl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
