# Generated by Django 3.1.7 on 2021-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0024_auto_20210318_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='admin_office',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
