# Generated by Django 3.1.7 on 2021-03-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0027_auto_20210322_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='data_review',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='date_firstfind',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='date_lastfind',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mat_bupe',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mat_mtd',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mat_ntrex',
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='walk_in_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='coe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='iop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='mh_tx',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='op',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='other_notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='wih_induction',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
