# Generated by Django 3.1.7 on 2021-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0028_auto_20210322_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='name_listed',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='street_address',
            new_name='street1',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='loc_suppl',
            new_name='street2',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='zip5',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc',
            old_name='street_address',
            new_name='street1',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc',
            old_name='loc_suppl',
            new_name='street2',
        ),
        migrations.RenameField(
            model_name='siterecs_hfp_fqhc',
            old_name='zip5',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='siterecs_other_srcs',
            old_name='address_suppl',
            new_name='name3',
        ),
        migrations.RenameField(
            model_name='siterecs_other_srcs',
            old_name='zip5',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_ftloc',
            old_name='phone_intake2',
            new_name='intake1',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_ftloc',
            old_name='phone_intake1',
            new_name='intake2',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_ftloc',
            old_name='zip5',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='certification_status',
            new_name='certification',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='name_dba',
            new_name='dba',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='date_full_certification',
            new_name='full_certification',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='name_program',
            new_name='program_name',
        ),
        migrations.RenameField(
            model_name='siterecs_samhsa_otp',
            old_name='street_address',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='mat_bupe',
            new_name='bu',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='dbhids_tad_id',
            new_name='id_dbhids_tad',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='hfp_fqhc_id',
            new_name='id_hfp_fqhc',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='samhsa_ftloc_id',
            new_name='id_samhsa_ftloc',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='samhsa_otp_id',
            new_name='id_samhsa_otp',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='mat_mtd',
            new_name='mu',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='name_program',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='name_site',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='mat_ntrex',
            new_name='nu',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='address_suppl',
            new_name='street1',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='url_site',
            new_name='website1',
        ),
        migrations.RenameField(
            model_name='sites_all',
            old_name='street_address',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='mat_bupe',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='mat_mtd',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='mat_ntrex',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_bupe',
        ),
        migrations.RemoveField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_mtd',
        ),
        migrations.RemoveField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_ntrex',
        ),
        migrations.RemoveField(
            model_name='sites_all',
            name='other_srcs_id',
        ),
        migrations.RemoveField(
            model_name='sites_all',
            name='zip5',
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='bu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='bui',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='bum',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='buu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='bwn',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=30),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='data_review',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='mdi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='mm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='mu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='nu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ref_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='state_usa',
            field=models.CharField(default='PA', max_length=30),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='vti',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='vtm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='vtrl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AddField(
            model_name='siterecs_hfp_fqhc',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='bu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=30),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='mu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='nu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='state_usa',
            field=models.CharField(default='PA', max_length=30),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='street1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='street2',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_otp',
            name='archival_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_otp',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=30),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='data_review',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='prim_care',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='state_usa',
            field=models.CharField(default='PA', max_length=30),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='street2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='telehealth',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='website2',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('Site closed', 'Site closed'), ('Data needs review', 'Data needs review'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='fqhc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mat_avail',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='pregnant_women_treated',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='telehealth_avail',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
    ]
