# Generated by Django 3.1.7 on 2021-07-17 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0029_auto_20210608_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ba_dbhids_tad',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('name_ba', models.CharField(max_length=50)),
                ('hh', models.BooleanField(blank=True, null=True)),
                ('hwm', models.BooleanField(blank=True, null=True)),
                ('rhl', models.BooleanField(blank=True, null=True)),
                ('rhs', models.BooleanField(blank=True, null=True)),
                ('wm', models.BooleanField(blank=True, null=True)),
                ('uo', models.BooleanField(blank=True, null=True)),
                ('date_firstfind', models.DateField()),
                ('date_lastfind', models.DateField(blank=True, null=True)),
                ('date_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('archival_only', models.BooleanField()),
                ('why_hidden', models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150)),
                ('data_review', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Table_info',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('update_recency', models.DateField()),
                ('records_count', models.IntegerField(blank=True, null=True)),
                ('facility_type', models.CharField(max_length=250)),
                ('source_range', models.CharField(max_length=120)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('filters', models.CharField(blank=True, max_length=5000)),
                ('display_cols', models.CharField(blank=True, max_length=500)),
                ('hide_cols', models.CharField(blank=True, max_length=500)),
                ('annual_updates', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Siterecs_dbhids_sites_all_lookup',
            new_name='Lookup_siterecs_dbhids_tad',
        ),
        migrations.RenameModel(
            old_name='Siterecs_hfp_fqhc_sites_all_lookup',
            new_name='Lookup_siterecs_hfp_fqhc',
        ),
        migrations.RenameModel(
            old_name='sitesrecs_other_srcs_sitesall_lk',
            new_name='Lookup_siterecs_other_srcs',
        ),
        migrations.RenameModel(
            old_name='Sites_ftloc',
            new_name='Lookup_siterecs_samhsa_ftloc',
        ),
        migrations.RenameModel(
            old_name='sites_site_recs_lookup',
            new_name='Lookup_siterecs_samhsa_otp',
        ),
        migrations.RenameField(
            model_name='siterecs_dbhids_tad',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='siterecs_other_srcs',
            old_name='pregnant_women_treated',
            new_name='pw',
        ),
        migrations.RenameField(
            model_name='siterecs_other_srcs',
            old_name='telehealth_avail',
            new_name='telehealth',
        ),
        migrations.RemoveField(
            model_name='sitecodes_samhsa_ftloc',
            name='filter_seq',
        ),
        migrations.RemoveField(
            model_name='sitecodes_samhsa_ftloc',
            name='mm_filters',
        ),
        migrations.RemoveField(
            model_name='sitecodes_samhsa_ftloc',
            name='ui_reference',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='bum',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='buu',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='bwn',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='iop',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mdi',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mh_tx',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='other_notes',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='vtm',
        ),
        migrations.RemoveField(
            model_name='siterecs_dbhids_tad',
            name='vtrl',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='bupe_type',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='corr_date',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='corr_notes',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='corr_source',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='insurance_notes',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='pregnant_women_notes',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='services',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='siterecs_other_srcs',
            name='telehealth_notes',
        ),
        migrations.RemoveField(
            model_name='siterecs_samhsa_ftloc',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='additional_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='asm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ba',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ccc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='date_firstfind',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='date_lastfind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='f17',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='f44',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='f47',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='f92',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='hs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='male',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='mhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='name_ba',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='oit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='phone2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='pw',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='sp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ad',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ah',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='asm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ba',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ccc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='data_review',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='dvh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='fem',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='gl',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='hh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='hs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='hwm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='male',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='mc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='md',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='mhs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='oi',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='oit',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='op',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='otp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='pa',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='phone1',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='phone2',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='phone3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='prim_care',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref_notes',
            field=models.CharField(blank=True, max_length=299),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='rhl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='rhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='se',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='sp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ta',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='uo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='wm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='dvh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='intake_prompt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='oi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='zip5',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ad',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ah',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='asm',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ba',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ccc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='dvh',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='fem',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='gl',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='hh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='hs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='hwm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='id_other_srcs',
            field=models.ManyToManyField(blank=True, null=True, to='bupehandler.Siterecs_other_srcs'),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='male',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Yes', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='mc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='md',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='mhs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='name3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='oi',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='oit',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='op',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='otp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='pa',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='phone3',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='pw',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref_notes',
            field=models.CharField(blank=True, max_length=299),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='rhl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='rhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='se',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='sp',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ta',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='Unclear', max_length=20),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='uo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='wm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecodes_samhsa_ftloc',
            name='category_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='sitecodes_samhsa_ftloc',
            name='category_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='sitecodes_samhsa_ftloc',
            name='service_description',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='sitecodes_samhsa_ftloc',
            name='service_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='data_review',
            field=models.CharField(blank=True, default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='mat_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='ref_address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='street2',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='walk_in_hours',
            field=models.CharField(blank=True, default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='date_lastfind',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='name_short',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='name_system',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='phone2',
            field=models.CharField(blank=True, default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='state_usa',
            field=models.CharField(default='PA', max_length=30),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='street2',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_hfp_fqhc',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='fqhc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='name2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='name3',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='state_usa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='street1',
            field=models.CharField(blank=True, default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='street2',
            field=models.CharField(blank=True, default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='website1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='website2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='date_firstfind',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='intake1',
            field=models.CharField(blank=True, default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='intake2',
            field=models.CharField(blank=True, default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_avail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='mat_misc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='name2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='state_usa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='street2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_ftloc',
            name='zip4',
            field=models.CharField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='data_review',
            field=models.CharField(blank=True, default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='date_firstfind',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='dba',
            field=models.CharField(blank=True, default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='state_usa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='siterecs_samhsa_otp',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='archival_only',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='data_review',
            field=models.CharField(blank=True, max_length=499, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='fqhc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mu',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unclear', 'Unclear')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='name2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='phone1',
            field=models.CharField(blank=True, default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='phone2',
            field=models.CharField(blank=True, default=None, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='state_usa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='street1',
            field=models.CharField(blank=True, default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='street2',
            field=models.CharField(blank=True, default=None, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='website1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='website2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='why_hidden',
            field=models.CharField(blank=True, choices=[('No MAT?', 'No MAT?'), ('Site closed', 'Site closed'), ('Not a practice site', 'Not a practice site'), ('Record redundant', 'Record redundant'), ('Source removed record', 'Source removed record'), ('Too far from Philadelphia?', 'Too far from Philadelphia?'), ('Data needs review', 'Data needs review'), ('Other', 'Other')], default='Data needs review', max_length=150),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.CreateModel(
            name='Lookup_ba_dbhids_tad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samhsa_oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.ba_dbhids_tad')),
                ('sites_all_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bupehandler.sites_all')),
            ],
        ),
        migrations.AddField(
            model_name='ba_dbhids_tad',
            name='site_id',
            field=models.ManyToManyField(through='bupehandler.Lookup_ba_dbhids_tad', to='bupehandler.Sites_all'),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='id_ba_tad',
            field=models.ManyToManyField(blank=True, null=True, to='bupehandler.Ba_dbhids_tad'),
        ),
    ]
