# Generated by Django 3.1.7 on 2021-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0031_auto_20210724_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites_all',
            name='dental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='hcv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='ref7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_ba_tad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_dbhids_tad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_fqhc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_other_srcs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_samhsa_ftloc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='src_samhsa_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='wdc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='ad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='ah',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='asm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='ba',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='bu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='ccc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='dvh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='fem',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='fqhc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='gl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='hs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='male',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mat_avail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='md',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='mu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='nu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='oi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='oit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='op',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='pa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='prim_care',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='pw',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='se',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='sp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='ta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siterecs_other_srcs',
            name='telehealth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='ad',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='ah',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='asm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='ba',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='bu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='ccc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='dvh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='fem',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='fqhc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='gl',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='hs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='male',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mat_avail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='md',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mhs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='mu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='nu',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='oi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='oit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='op',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='pa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='prim_care',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='pw',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='se',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='sp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='ta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites_all',
            name='telehealth',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
