# Generated by Django 3.1.7 on 2021-10-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0032_auto_20210827_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ai01',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ai02',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ai03',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ai04',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_dbhids_tad',
            name='ai05',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='dental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='hcv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='ref7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='vet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siterecs_other_srcs',
            name='wdc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siterecs_samhsa_ftloc',
            name='data_review',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='sites_all',
            name='vet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
