# Generated by Django 3.1.7 on 2021-10-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bupehandler', '0033_auto_20211012_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siterecs_dbhids_tad',
            name='additional_info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
