from rest_framework import serializers
from .models import Sitecodes_samhsa_ftloc, Siterecs_samhsa_ftloc, Siterecs_samhsa_otp, Siterecs_dbhids_tad, Siterecs_other_srcs, Sites_all

class Sitecodes_samhsa_ftlocSerializer(serializers.ModelSerializer):
    class Meta:
        model = Sitecodes_samhsa_ftloc
        fields = ['service_code', 'category_code', 'category_name', 'sa_listings_match', 'mm_highlights', 'service_name','service_description', 'date_update']


class Siterecs_samhsa_ftlocSerializer(serializers.ModelSerializer):
    class Meta:
        model = Siterecs_samhsa_ftloc
        fields = [
    'oid',
    'site_id',
    'date_firstfind',
    'date_lastfind',
    'name1',
    'name2',
    'street1',
    'street2',
    'city',
    'state_usa',
    'zip5',
    'zip4',
    'county',
    'phone',
    'phone_intake1',
    'phone_intake2',
    'website',
    'latitude',
    'longitude',
    'type_facility',
    'otpa',
    'otp',
    'bu',
    'ub',
    'bum',
    'bmw',
    'bsdm',
    'bwn',
    'bwon',
    'beri',
    'db_field',
    'mu',
    'meth',
    'mm',
    'mmw',
    'dm',
    'nu',
    'un',
    'nxn',
    'vtrl',
    'rpn',
    'dt',
    'moa',
    'noop',
    'nmoa',
    'pain',
    'hh',
    'ubn',
    'cbt',
    'dbt',
    'saca',
    'trc',
    'rebt',
    'smon',
    'smpd',
    'smop',
    'hi',
    'res',
    'op',
    'rs',
    'rl',
    'rd',
    'od',
    'omb',
    'odt',
    'oit',
    'ort',
    'hid',
    'hit',
    'ct',
    'gh',
    'psyh',
    'vamc',
    'tbg',
    'ih',
    'stg',
    'lccg',
    'ddf',
    'stag',
    'stmh',
    'stdh',
    'hla',
    'jc',
    'carf',
    'ncqa',
    'coa',
    'hfap',
    'np',
    'sf',
    'md',
    'mc',
    'si',
    'pi_field',
    'mi',
    'atr',
    'fsa',
    'ss',
    'pa',
    'ah',
    'sp',
    'co',
    'gl',
    'vet',
    'adm',
    'mf',
    'cj',
    'se',
    'ad',
    'pw',
    'wn',
    'mn',
    'hv',
    'trma',
    'xa',
    'dv',
    'tay',
    'nsc',
    'adtx',
    'bdtx',
    'cdtx',
    'mdtx',
    'odtx',
    'tgd',
    'tid',
    'ico',
    'gco',
    'fco',
    'mco',
    'twfa',
    'bia',
    'cmi',
    'moti',
    'ang',
    'mxm',
    'crv',
    'relp',
    'bc',
    'chld',
    'yad',
    'adlt',
    'fem',
    'male',
    'bmo',
    'mo',
    'du',
    'duo',
    'acc',
    'acm',
    'acu',
    'add_field',
    'baba',
    'ccc',
    'cmha',
    'csaa',
    'daut',
    'dp',
    'dsf',
    'dvfp',
    'eih',
    'emp',
    'haec',
    'heoh',
    'hivt',
    'isc',
    'itu',
    'mhs',
    'mpd',
    'opc',
    'sae',
    'shb',
    'shc',
    'shg',
    'smhd',
    'ssa',
    'ssd',
    'stdt',
    'ta',
    'taec',
    'tbs',
    'cm',
    'fpsy',
    'hs',
    'nrt',
    'peer',
    'stu',
    'tcc',
    'pvtp',
    'pvtn',
    'vo',
    'sumh',
    'inpe',
    'rpe',
    'pc',
    'naut',
    'nmaut',
    'acma',
    'pmat',
    'auinpe',
    'aurpe',
    'aupc',
    'ulc',
    'mhiv',
    'mhcv',
    'lfxd',
    'clnd',
    'copsu',
    'daof',
    'mst',
    'noe',
    'ofd',
    'rc',
    'piec',
    'mdet',
    'voc',
    'hav',
    'hbv',
    'audo',
    'f17',
    'f19',
    'f25',
    'f28',
    'f30',
    'f31',
    'f35',
    'f36',
    'f37',
    'f4',
    'f42',
    'f43',
    'f47',
    'f66',
    'f67',
    'f70',
    'f81',
    'f92',
    'n13',
    'n18',
    'n23',
    'n24',
    'n40',
    'date_update']


class Siterecs_samhsa_otpSerializer(serializers.ModelSerializer):
    class Meta:
        model = Siterecs_samhsa_otp
        fields = ['oid',
            'name_program','name_dba','street_address','city','state_usa','zipcode',
            'phone','certification_status','date_full_certification','date_firstfind','date_lastfind',
            'data_review','date_update']

class Siterecs_dbhids_tadSerializer(serializers.ModelSerializer):
    class Meta:
        model = Siterecs_dbhids_tad
        fields = ['oid','site_id','date_firstfind','date_lastfind','data_review','date_update']

class Siterecs_other_srcsSerializer(serializers.ModelSerializer):
    class Meta:
        model = Siterecs_other_srcs
        fields = ['oid','name1','name2','website1','website2','street_address','address_suppl',
        'zip5','fqhc','mat_avail','mat_bupe','mat_mtd','mat_ntrex','bupe_type','telehealth_avail',
        'telehealth_notes','insurance_notes','pregnant_women_treated','pregnant_women_notes',
        'insurance','clients','services','setting','corr_date','corr_source','corr_notes',
        'date_update']

class Sites_allSerializer(serializers.ModelSerializer):
    class Meta:
        model = Sites_all
        fields = ['oid','samhsa_ftloc_id','samhsa_otp_id','dbhids_tad_id','other_srcs_id','name_site','name_program',
        'street_address','address_suppl','zip5','latitude','longitude','mat_avail','mat_bupe','mat_mtd',
        'mat_ntrex','fqhc','date_update']
    